CREATE TABLE Prospect
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	TeamId INT FOREIGN KEY REFERENCES Team (Id) NOT NULL,
	Height INT NOT NULL,
	Weight INT NOT NULL,
	PositionId INT FOREIGN KEY REFERENCES Position (Id) NOT NULL,
	HandednessId INT FOREIGN KEY REFERENCES Handedness (Id) NOT NULL,
	BirthDay DATE NOT NULL,
	DraftYear INT NOT NULL,
	BirthCity VARCHAR(255),
	BirthCountry VARCHAR(255),
	Notes VARCHAR (2047)
);

CREATE UNIQUE INDEX Prospect_Name_BirthDay
ON Prospect (Name, BirthDay);