CREATE TABLE Team
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	LeagueId INT FOREIGN KEY REFERENCES League(Id) NOT NULL
);

CREATE UNIQUE INDEX Team_Name_League
ON Team (Name, LeagueId);